version: '3.8'

services:
  # Backend API
  backend:
    build: ./backend
    container_name: backlog_backend
    environment:
      # Database
      - POSTGRES_USER=backlog_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-backlog_super_secure_password_2024}
      - POSTGRES_HOST=172.17.0.1
      - POSTGRES_PORT=5433
      - POSTGRES_DB=student_planner
      
      # JWT & Security
      - SECRET_KEY=${SECRET_KEY:-super-secret-production-key-change-this-in-env}
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
      - DEBUG=false
      
      # CORS & URLs
      - BACKEND_CORS_ORIGINS=["https://unl-backlog.duckdns.org", "http://localhost:3001"]
      - FRONTEND_URL=https://unl-backlog.duckdns.org
      - BACKEND_URL=https://unl-backlog.duckdns.org
      
      # VAPID Keys for Push Notifications
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - VAPID_SUBJECT=mailto:admin@unl-backlog.duckdns.org
      
      # OAuth Credentials
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=https://unl-backlog.duckdns.org/auth/google/callback
      
      - VK_CLIENT_ID=${VK_CLIENT_ID}
      - VK_CLIENT_SECRET=${VK_CLIENT_SECRET}
      - VK_REDIRECT_URI=https://unl-backlog.duckdns.org/auth/vk/callback
      
      # Telegram (optional)
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - ./backend/uploads:/app/uploads
    ports:
      - "8010:8000"
    networks:
      - backlog_network
    restart: unless-stopped

  # Frontend
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        NEXT_PUBLIC_API_URL: https://unl-backlog.duckdns.org/api/v1
        NEXT_PUBLIC_FRONTEND_URL: https://unl-backlog.duckdns.org
    container_name: backlog_frontend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://unl-backlog.duckdns.org/api/v1
      - NEXT_PUBLIC_FRONTEND_URL=https://unl-backlog.duckdns.org
    ports:
      - "3010:3000"
    depends_on:
      - backend
    networks:
      - backlog_network
    restart: unless-stopped

networks:
  backlog_network:
    driver: bridge 