version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: backlog_postgres
    environment:
      - POSTGRES_USER=backlog_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-backlog_super_secure_password_2024}
      - POSTGRES_DB=student_planner
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - backlog_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U backlog_user -d student_planner"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build: ./backend
    container_name: backlog_backend
    environment:
      # Database
      - POSTGRES_USER=backlog_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-backlog_super_secure_password_2024}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=student_planner
      
      # JWT & Security
      - SECRET_KEY=${SECRET_KEY:-super-secret-production-key-change-this-in-env}
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
      - DEBUG=true
      
      # CORS & URLs
      - BACKEND_CORS_ORIGINS=["https://unl-backlog.duckdns.org", "http://localhost:3001"]
      - FRONTEND_URL=https://unl-backlog.duckdns.org
      - BACKEND_URL=https://unl-backlog.duckdns.org
      
      # VAPID Keys for Push Notifications
      - VAPID_PRIVATE_KEY=LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZzVlN0thc0JDT2tKT3ZGdjAKcktIR0pnSG1TWDUvT1lRa3ROT1RUSTY2ZTR1aFJBTkNBQVFaSEthZnpaREZseCtqWnRWUzlnWkJabFhSU0lrCkpJL1EzSVpQZjFEZTRhS0hGcUJiV2ZZcWxCVG9WNWxQSjFYb25wWXltTi9BKzRUQjZBakxUOFl6Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
      - VAPID_PUBLIC_KEY=BBkcpp_NkMWXH6uNm1VL2BkFmVdFIiQkj9Dchk9_UN7hoocWoFtZ9iqUFOhXmU8nVeieljKY38D7hMHoCMtPxjM
      - VAPID_SUBJECT=mailto:admin@unl-backlog.duckdns.org
      
    volumes:
      - ./backend/uploads:/app/uploads
    ports:
      - "8010:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backlog_network
    restart: unless-stopped

  # Frontend
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        NEXT_PUBLIC_API_URL: https://unl-backlog.duckdns.org
        NEXT_PUBLIC_FRONTEND_URL: https://unl-backlog.duckdns.org
        NEXT_PUBLIC_VAPID_PUBLIC_KEY: BBkcpp_NkMWXH6uNm1VL2BkFmVdFIiQkj9Dchk9_UN7hoocWoFtZ9iqUFOhXmU8nVeieljKY38D7hMHoCMtPxjM
    container_name: backlog_frontend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://unl-backlog.duckdns.org
      - NEXT_PUBLIC_FRONTEND_URL=https://unl-backlog.duckdns.org
      - NEXT_PUBLIC_VAPID_PUBLIC_KEY=BBkcpp_NkMWXH6uNm1VL2BkFmVdFIiQkj9Dchk9_UN7hoocWoFtZ9iqUFOhXmU8nVeieljKY38D7hMHoCMtPxjM
    ports:
      - "3010:3000"
    depends_on:
      - backend
    networks:
      - backlog_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  backlog_network:
    driver: bridge 